// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function GetAWSIdentity():Promise<gui.AWSIdentityResult>;

export function ParamAddTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ParamDelete(arg1:string):Promise<gui.ParamDeleteResult>;

export function ParamDiff(arg1:string,arg2:string):Promise<gui.ParamDiffResult>;

export function ParamList(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:number,arg6:string):Promise<gui.ParamListResult>;

export function ParamLog(arg1:string,arg2:number):Promise<gui.ParamLogResult>;

export function ParamRemoveTag(arg1:string,arg2:string):Promise<void>;

export function ParamSet(arg1:string,arg2:string,arg3:string):Promise<gui.ParamSetResult>;

export function ParamShow(arg1:string):Promise<gui.ParamShowResult>;

export function SecretAddTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SecretCreate(arg1:string,arg2:string):Promise<gui.SecretCreateResult>;

export function SecretDelete(arg1:string,arg2:boolean):Promise<gui.SecretDeleteResult>;

export function SecretDiff(arg1:string,arg2:string):Promise<gui.SecretDiffResult>;

export function SecretList(arg1:string,arg2:boolean,arg3:string,arg4:number,arg5:string):Promise<gui.SecretListResult>;

export function SecretLog(arg1:string,arg2:number):Promise<gui.SecretLogResult>;

export function SecretRemoveTag(arg1:string,arg2:string):Promise<void>;

export function SecretRestore(arg1:string):Promise<gui.SecretRestoreResult>;

export function SecretShow(arg1:string):Promise<gui.SecretShowResult>;

export function SecretUpdate(arg1:string,arg2:string):Promise<gui.SecretUpdateResult>;

export function StagingAdd(arg1:string,arg2:string,arg3:string):Promise<gui.StagingAddResult>;

export function StagingAddTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<gui.StagingAddTagResult>;

export function StagingApply(arg1:string,arg2:boolean):Promise<gui.StagingApplyResult>;

export function StagingCancelAddTag(arg1:string,arg2:string,arg3:string):Promise<gui.StagingCancelAddTagResult>;

export function StagingCancelRemoveTag(arg1:string,arg2:string,arg3:string):Promise<gui.StagingCancelRemoveTagResult>;

export function StagingCheckStatus(arg1:string,arg2:string):Promise<gui.StagingCheckStatusResult>;

export function StagingDelete(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<gui.StagingDeleteResult>;

export function StagingDiff(arg1:string,arg2:string):Promise<gui.StagingDiffResult>;

export function StagingEdit(arg1:string,arg2:string,arg3:string):Promise<gui.StagingEditResult>;

export function StagingRemoveTag(arg1:string,arg2:string,arg3:string):Promise<gui.StagingRemoveTagResult>;

export function StagingReset(arg1:string):Promise<gui.StagingResetResult>;

export function StagingStatus():Promise<gui.StagingStatusResult>;

export function StagingUnstage(arg1:string,arg2:string):Promise<gui.StagingUnstageResult>;
