// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAWSIdentity() {
  return window['go']['gui']['App']['GetAWSIdentity']();
}

export function ParamAddTag(arg1, arg2, arg3) {
  return window['go']['gui']['App']['ParamAddTag'](arg1, arg2, arg3);
}

export function ParamDelete(arg1) {
  return window['go']['gui']['App']['ParamDelete'](arg1);
}

export function ParamDiff(arg1, arg2) {
  return window['go']['gui']['App']['ParamDiff'](arg1, arg2);
}

export function ParamList(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['gui']['App']['ParamList'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ParamLog(arg1, arg2) {
  return window['go']['gui']['App']['ParamLog'](arg1, arg2);
}

export function ParamRemoveTag(arg1, arg2) {
  return window['go']['gui']['App']['ParamRemoveTag'](arg1, arg2);
}

export function ParamSet(arg1, arg2, arg3) {
  return window['go']['gui']['App']['ParamSet'](arg1, arg2, arg3);
}

export function ParamShow(arg1) {
  return window['go']['gui']['App']['ParamShow'](arg1);
}

export function SecretAddTag(arg1, arg2, arg3) {
  return window['go']['gui']['App']['SecretAddTag'](arg1, arg2, arg3);
}

export function SecretCreate(arg1, arg2) {
  return window['go']['gui']['App']['SecretCreate'](arg1, arg2);
}

export function SecretDelete(arg1, arg2) {
  return window['go']['gui']['App']['SecretDelete'](arg1, arg2);
}

export function SecretDiff(arg1, arg2) {
  return window['go']['gui']['App']['SecretDiff'](arg1, arg2);
}

export function SecretList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['gui']['App']['SecretList'](arg1, arg2, arg3, arg4, arg5);
}

export function SecretLog(arg1, arg2) {
  return window['go']['gui']['App']['SecretLog'](arg1, arg2);
}

export function SecretRemoveTag(arg1, arg2) {
  return window['go']['gui']['App']['SecretRemoveTag'](arg1, arg2);
}

export function SecretRestore(arg1) {
  return window['go']['gui']['App']['SecretRestore'](arg1);
}

export function SecretShow(arg1) {
  return window['go']['gui']['App']['SecretShow'](arg1);
}

export function SecretUpdate(arg1, arg2) {
  return window['go']['gui']['App']['SecretUpdate'](arg1, arg2);
}

export function StagingAdd(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StagingAdd'](arg1, arg2, arg3);
}

export function StagingAddTag(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['StagingAddTag'](arg1, arg2, arg3, arg4);
}

export function StagingApply(arg1, arg2) {
  return window['go']['gui']['App']['StagingApply'](arg1, arg2);
}

export function StagingCancelAddTag(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StagingCancelAddTag'](arg1, arg2, arg3);
}

export function StagingCancelRemoveTag(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StagingCancelRemoveTag'](arg1, arg2, arg3);
}

export function StagingCheckStatus(arg1, arg2) {
  return window['go']['gui']['App']['StagingCheckStatus'](arg1, arg2);
}

export function StagingDelete(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['StagingDelete'](arg1, arg2, arg3, arg4);
}

export function StagingDiff(arg1, arg2) {
  return window['go']['gui']['App']['StagingDiff'](arg1, arg2);
}

export function StagingEdit(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StagingEdit'](arg1, arg2, arg3);
}

export function StagingRemoveTag(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StagingRemoveTag'](arg1, arg2, arg3);
}

export function StagingReset(arg1) {
  return window['go']['gui']['App']['StagingReset'](arg1);
}

export function StagingStatus() {
  return window['go']['gui']['App']['StagingStatus']();
}

export function StagingUnstage(arg1, arg2) {
  return window['go']['gui']['App']['StagingUnstage'](arg1, arg2);
}
