// Code generated by "stringer -type=RevisionContentType -output=revisioning_string.gen.go"; DO NOT EDIT.

package revisioning

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RevisionContentTypeUnknown-0]
	_ = x[RevisionContentTypeString-1]
	_ = x[RevisionContentTypeBytes-2]
}

const _RevisionContentType_name = "RevisionContentTypeUnknownRevisionContentTypeStringRevisionContentTypeBytes"

var _RevisionContentType_index = [...]uint8{0, 26, 51, 75}

func (i RevisionContentType) String() string {
	if i < 0 || i >= RevisionContentType(len(_RevisionContentType_index)-1) {
		return "RevisionContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RevisionContentType_name[_RevisionContentType_index[i]:_RevisionContentType_index[i+1]]
}
