version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - depguard
    - forbidigo
  settings:
    cyclop:
      max-complexity: 30
    funlen:
      lines: 200
      statements: 100
    gocognit:
      min-complexity: 60
    exhaustive:
      default-signifies-exhaustive: true
    depguard:
      rules:
        aws-sdk:
          files:
            - "!**/internal/api/**"
            - "!**/internal/infra/**"
          deny:
            - pkg: "github.com/aws/aws-sdk-go-v2/service/ssm"
              desc: "Use github.com/mpyw/suve/internal/api/paramapi instead"
            - pkg: "github.com/aws/aws-sdk-go-v2/service/ssm/types"
              desc: "Use github.com/mpyw/suve/internal/api/paramapi instead"
            - pkg: "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
              desc: "Use github.com/mpyw/suve/internal/api/secretapi instead"
            - pkg: "github.com/aws/aws-sdk-go-v2/service/secretsmanager/types"
              desc: "Use github.com/mpyw/suve/internal/api/secretapi instead"
    forbidigo:
      forbid:
        - pattern: 'fmt\.Fprint(ln|f)?'
          msg: "Use output package functions instead of fmt.Fprint*"
      exclude-godoc-examples: true
      analyze-types: true

issues:
  exclude-rules:
    # Allow fmt.Fprint* in output/output.go (implements the wrapper functions)
    - path: "internal/cli/output/output\\.go"
      linters:
        - forbidigo
    # Allow fmt.Fprint* in test files
    - path: "_test\\.go$"
      linters:
        - forbidigo
    # Allow fmt.Fprint* in e2e tests
    - path: "e2e/"
      linters:
        - forbidigo

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mpyw/suve)
      custom-order: true
