version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: all
  disable:
    # Struct/interface style - too verbose or not idiomatic
    - exhaustruct      # Requires all struct fields
    - ireturn          # Interface returns are idiomatic Go
    - varnamelen       # Short names in small scopes are fine
    - inamedparam      # Interface named params not always needed
    - nonamedreturns   # Named returns useful for documentation
    # Error handling style - too strict
    - err113           # Dynamic errors are acceptable in CLI tools
    # Wrapping/formatting - handled by other tools or not useful
    - wrapcheck        # Internal packages don't need wrapping
    - nlreturn         # Pure style preference
    - wsl              # Pure style preference (wsl_v5 included)
    - lll              # Line length - use editor settings
    - tagliatelle      # JSON tag naming style preference
    # Test style - not all patterns are useful
    - paralleltest     # Not all tests benefit from parallel
    - testpackage      # Internal tests are common and useful
    # Code organization - too opinionated
    - gochecknoglobals # Package-level vars are intentional (errors, configs)
    - gochecknoinits   # init() is sometimes needed
    - funcorder        # Function order is contextual
    - godox            # TODO/FIXME comments are fine during development
    # Performance micro-optimizations - premature
    - prealloc         # Premature optimization
    - mnd              # Magic numbers are often contextually clear
    # i18n - not needed for this CLI tool
    - gosmopolitan     # No i18n requirements
    # Duplicate detection - handled by fzdupl instead
    - dupl             # fzdupl is more precise
    # We configure depguard ourselves
    - depguard
    # Style preferences - too strict for this codebase
    - gocritic         # ifElseChain style is acceptable
    - godoclint        # Multiple package comments are acceptable
    - godot            # Comment punctuation is not critical
    - goprintffuncname # printf naming convention not always useful
    - maintidx         # Test functions are naturally large
    - intrange         # Go 1.22+ range syntax not required
    # Modernization suggestions - would require significant refactoring
    - nestif           # Complex nesting is sometimes necessary for clarity
    - modernize        # Go 1.22+ modernizations (rangeint, mapsloop, etc.)
    - mirror           # bytes.Index allocation warnings are premature optimization
    # Whitespace and style - pure stylistic preferences
    - wsl              # Whitespace linter - pure style preference
    - wsl_v5           # Whitespace linter v5 - pure style preference (already excluded)
    - revive           # Many style-based rules that are too strict
    # Context requirements - would require significant API changes
    - noctx            # Context in net/exec calls - major refactoring
    # Error handling style - valid patterns in this codebase
    - noinlineerr      # Inline error handling is idiomatic
    - nilerr           # Sometimes returning nil error with logged message is intentional
    - nilnil           # Sometimes returning nil, nil is valid (no result, no error)
    # Test patterns - not all patterns apply
    - usetesting       # t.TempDir vs os.MkdirTemp - both valid
    - testifylint      # Testify assertion style preferences
    - thelper          # Not all helper functions need t.Helper()
    - tparallel        # Not all tests benefit from parallel
    # Too strict performance optimizations
    - perfsprint       # fmt.Sprintf -> string concat is often less readable
    # Package/variable naming - too strict
    - predeclared      # Package names like 'delete' are intentional
    # Parameter usage - sometimes unused params are needed for interface compliance
    - unparam          # Unused params are sometimes intentional for API consistency
  enable:
    - depguard
  exclusions:
    rules:
      # Allow fmt.Fprint* in output/output.go (implements the wrapper functions)
      - path: "internal/cli/output/output\\.go"
        linters:
          - forbidigo
        text: "fmt\\.Fprint"
      # Allow fmt.Fprint* in e2e tests
      - path: "e2e/"
        linters:
          - forbidigo
        text: "fmt\\.Fprint"
      # Allow context.Background() in entry points (main.go is the root)
      - path: "cmd/suve/main\\.go"
        linters:
          - forbidigo
        text: "context\\.Background"
  settings:
    cyclop:
      max-complexity: 30
    funlen:
      lines: 200
      statements: 100
    gocognit:
      min-complexity: 60
    exhaustive:
      default-signifies-exhaustive: true
    depguard:
      rules:
        aws-sdk:
          files:
            - "!**/internal/api/**"
            - "!**/internal/infra/**"
          deny:
            - pkg: "github.com/aws/aws-sdk-go-v2/service/ssm"
              desc: "Use github.com/mpyw/suve/internal/api/paramapi instead"
            - pkg: "github.com/aws/aws-sdk-go-v2/service/ssm/types"
              desc: "Use github.com/mpyw/suve/internal/api/paramapi instead"
            - pkg: "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
              desc: "Use github.com/mpyw/suve/internal/api/secretapi instead"
            - pkg: "github.com/aws/aws-sdk-go-v2/service/secretsmanager/types"
              desc: "Use github.com/mpyw/suve/internal/api/secretapi instead"
    forbidigo:
      forbid:
        - pattern: 'fmt\.Fprint(ln|f)?'
          msg: "Use output package functions instead of fmt.Fprint*"
        - pattern: 'context\.Background\(\)'
          msg: "Use context from caller or t.Context() in tests. Only allowed in main.go and daemon entry points."
        - pattern: 'context\.TODO\(\)'
          msg: "Use context from caller or t.Context() in tests"
      exclude-godoc-examples: true
      analyze-types: true

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mpyw/suve)
      custom-order: true
