# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: suve

before:
  hooks:
    - go mod tidy

builds:
  # =============================================================================
  # suve: Integrated CLI + GUI (--gui flag)
  # macOS/Linux: CGO enabled, production tag
  # Windows: CGO disabled (CLI only, GUI stub)
  # Note: Linux arm64 GUI requires native arm64 runner (CGO cross-compile not supported)
  # =============================================================================
  - id: suve-darwin-amd64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-darwin-arm64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-linux-amd64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-windows-amd64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-windows-arm64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  # =============================================================================
  # suve-cli: CLI only (no GUI dependency, no CGO)
  # =============================================================================
  - id: suve-cli-darwin-amd64
    main: ./cmd/suve-cli
    binary: suve-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-cli-darwin-arm64
    main: ./cmd/suve-cli
    binary: suve-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-cli-linux-amd64
    main: ./cmd/suve-cli
    binary: suve-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-cli-linux-arm64
    main: ./cmd/suve-cli
    binary: suve-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-cli-windows-amd64
    main: ./cmd/suve-cli
    binary: suve-cli
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-cli-windows-arm64
    main: ./cmd/suve-cli
    binary: suve-cli
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  # =============================================================================
  # suve-gui: GUI only (CGO required, macOS/Linux amd64 only)
  # Note: Linux arm64 requires native arm64 runner (CGO cross-compile not supported)
  # =============================================================================
  - id: suve-gui-darwin-amd64
    main: ./cmd/suve-gui
    binary: suve-gui
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w

  - id: suve-gui-darwin-arm64
    main: ./cmd/suve-gui
    binary: suve-gui
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    tags:
      - production
    ldflags:
      - -s -w

  - id: suve-gui-linux-amd64
    main: ./cmd/suve-gui
    binary: suve-gui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w

# =============================================================================
# Archives: Separate per binary type
# =============================================================================
archives:
  # suve (integrated CLI + GUI)
  - id: suve
    builds:
      - suve-darwin-amd64
      - suve-darwin-arm64
      - suve-linux-amd64
      - suve-windows-amd64
      - suve-windows-arm64
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  # suve-cli (CLI only)
  - id: suve-cli
    builds:
      - suve-cli-darwin-amd64
      - suve-cli-darwin-arm64
      - suve-cli-linux-amd64
      - suve-cli-linux-arm64
      - suve-cli-windows-amd64
      - suve-cli-windows-arm64
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  # suve-gui (GUI only, macOS/Linux amd64)
  - id: suve-gui
    builds:
      - suve-gui-darwin-amd64
      - suve-gui-darwin-arm64
      - suve-gui-linux-amd64
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: suve
    ids:
      - suve
    repository:
      owner: mpyw
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/mpyw/suve"
    description: "Git-like CLI for AWS Parameter Store and Secrets Manager"
    license: "MIT"
    install: |
      bin.install "suve"
    test: |
      system "#{bin}/suve", "--version"

release:
  github:
    owner: mpyw
    name: suve
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
