# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: suve

before:
  hooks:
    - go mod tidy

builds:
  # =============================================================================
  # suve: Integrated CLI + GUI
  # macOS/Linux: CGO enabled (required for webkit2gtk)
  # Windows: CGO not required (Wails uses pure Go webview2loader)
  # All platforms use production tag for GUI support
  # =============================================================================
  - id: suve-darwin-amd64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-darwin-arm64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-linux-amd64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-linux-arm64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-windows-amd64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

  - id: suve-windows-arm64
    main: ./cmd/suve
    binary: suve
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
    tags:
      - production
    ldflags:
      - -s -w
      - -X github.com/mpyw/suve/internal/cli/commands.Version={{.Version}}

archives:
  - id: suve
    builds:
      - suve-darwin-amd64
      - suve-darwin-arm64
      - suve-linux-amd64
      - suve-linux-arm64
      - suve-windows-amd64
      - suve-windows-arm64
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mpyw
    name: suve
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
