codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # 2 (unit + e2e) + 3 (platform: linux, darwin, windows) + 1 (gui) + 1 (gui-frontend)
        after_n_builds: 7
    patch:
      default:
        after_n_builds: 7
