codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # 2 (unit + e2e) + 3 (platform: linux, darwin, windows)
        after_n_builds: 5
    patch:
      default:
        after_n_builds: 5
