// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParamDelete(arg1) {
  return window['go']['main']['App']['ParamDelete'](arg1);
}

export function ParamDiff(arg1, arg2) {
  return window['go']['main']['App']['ParamDiff'](arg1, arg2);
}

export function ParamList(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParamList'](arg1, arg2, arg3);
}

export function ParamLog(arg1, arg2) {
  return window['go']['main']['App']['ParamLog'](arg1, arg2);
}

export function ParamSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParamSet'](arg1, arg2, arg3);
}

export function ParamShow(arg1) {
  return window['go']['main']['App']['ParamShow'](arg1);
}

export function SecretCreate(arg1, arg2) {
  return window['go']['main']['App']['SecretCreate'](arg1, arg2);
}

export function SecretDelete(arg1, arg2) {
  return window['go']['main']['App']['SecretDelete'](arg1, arg2);
}

export function SecretList(arg1, arg2) {
  return window['go']['main']['App']['SecretList'](arg1, arg2);
}

export function SecretLog(arg1, arg2) {
  return window['go']['main']['App']['SecretLog'](arg1, arg2);
}

export function SecretShow(arg1) {
  return window['go']['main']['App']['SecretShow'](arg1);
}

export function SecretUpdate(arg1, arg2) {
  return window['go']['main']['App']['SecretUpdate'](arg1, arg2);
}

export function StagingApply(arg1, arg2) {
  return window['go']['main']['App']['StagingApply'](arg1, arg2);
}

export function StagingReset(arg1) {
  return window['go']['main']['App']['StagingReset'](arg1);
}

export function StagingStatus() {
  return window['go']['main']['App']['StagingStatus']();
}
