// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ParamDiff(arg1:string,arg2:string):Promise<main.ParamDiffResult>;

export function ParamList(arg1:string,arg2:boolean,arg3:boolean):Promise<main.ParamListResult>;

export function ParamLog(arg1:string,arg2:number):Promise<main.ParamLogResult>;

export function ParamShow(arg1:string):Promise<main.ParamShowResult>;

export function SecretList(arg1:string,arg2:boolean):Promise<main.SecretListResult>;

export function SecretLog(arg1:string,arg2:number):Promise<main.SecretLogResult>;

export function SecretShow(arg1:string):Promise<main.SecretShowResult>;

export function StagingStatus():Promise<main.StagingStatusResult>;
