# nfpm configuration for generating .deb and .rpm packages (GUI version)
# https://nfpm.goreleaser.com/configuration/

name: suve
arch: "${GOARCH}"
platform: linux
version: "${VERSION}"
release: "1"
maintainer: "mpyw <mpyw628@gmail.com>"
description: |
  Git-like CLI/GUI for AWS Parameter Store and Secrets Manager
  .
  Provides familiar commands like show, log, diff, and a staging workflow
  for safe, reviewable changes to your AWS secrets and parameters.
  .
  This package includes GUI support via the -gui flag.
  Requires GTK3 and WebKit2GTK runtime libraries.
homepage: "https://github.com/mpyw/suve"
license: "MIT"

vendor: "mpyw"
section: "utils"
priority: "optional"

rpm:
  group: "Applications/System"

depends: []

# GUI dependencies - recommended but not strictly required
# Versions are detected from Wails source in CI
recommends:
  - ${GTK_DEB}
  - ${WEBKIT_DEB}

overrides:
  rpm:
    recommends:
      - ${GTK_RPM}
      - ${WEBKIT_RPM}

conflicts:
  - suve-cli

contents:
  - src: ./suve
    dst: /usr/bin/suve
    file_info:
      mode: 0755

  - src: ./LICENSE
    dst: /usr/share/doc/suve/copyright
    file_info:
      mode: 0644
